apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caldav-busy.fullname" . }}-config
  labels:
    {{- include "caldav-busy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}